# COMP90024 Project - Team 34
# Lokesh Sai Sri Harsha Sankarasetty, Melbourne, [1130612]
# Kanch Vatcharotayan, Melbourne, [1132855]
# Sai Deepthi Amancha, Melbourne, [1051388]
# Josin Saji Abraham, Melbourne, [1129428]
# Kush Garg, Melbourne, [1146696]

version: '3'
services:
  web:
    build: ./
    volumes:
      - mnt:/app
    ports:
      - "80:5123"
    env_file: .env

volumes:
  mnt:
    external:
      name: mnt