version: '3'

services:
    couchDB-master:
        image: couchdb:latest
        restart: always
        container_name: couchDB-master
        ports:
            - "5984:5984"
            - "4369:4369"
            - "9100-9200:9100-9200"
        links:
            - couchDB-slave1
            - couchDB-slave2
        environment: 
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=admintest
            - NODENAME=172.50.0.2
        volumes:
            - db-data-m1:/opt/couchdb/data
        networks:
            couchdb_cluster:
                ipv4_address: 172.50.0.2
          
    couchDB-slave1:
        image: couchdb:latest
        restart: always
        container_name: couchDB-slave1
        ports:
            - "5985:5984"
        environment: 
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=admintest
            - NODENAME=172.50.0.3
        volumes:
            - db-data-s1:/opt/couchdb/data
        networks:
            couchdb_cluster:
                ipv4_address: 172.50.0.3

    couchDB-slave2:
        image: couchdb:latest
        container_name: couchDB-slave2
        restart: always
        ports:
            - "5986:5984"
        environment: 
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=admintest
            - NODENAME=172.50.0.4
        volumes:
            - db-data-s2:/opt/couchdb/data
        networks:
            couchdb_cluster:
                ipv4_address: 172.50.0.4

volumes: 
    db-data-m1:
        external:
            name: db-data-m1
    db-data-s1:
        external:
            name: db-data-s1
    db-data-s2:
        external:
            name: db-data-s2

networks:
    couchdb_cluster:
        driver: bridge
        ipam:
            config:
                - subnet: 172.50.0.0/16